import type { FilePatch, JobBuildPreview } from "@fig2code/spec";
import { createGitHostProvider } from "@fig2code/git-host";
import type { StoredJob } from "./job-store.js";

export interface OpenJobPullRequestInput {
  stored: StoredJob;
  targetBranch: string;
  patches?: FilePatch[];
  previewFileOverrides?: Array<{ path: string; role: string; content: string }>;
}

export interface OpenJobPullRequestResult {
  prUrl: string;
  prNumber?: number;
  headBranch: string;
}

function slugify(value: string): string {
  return value
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

export function buildPatchesFromJobPreview(
  buildPreview: JobBuildPreview,
  overrides?: Array<{ path: string; content: string }>,
): FilePatch[] {
  const overrideMap = new Map(
    (overrides ?? []).map((entry) => [entry.path, entry.content] as const),
  );
  const patches = new Map<string, FilePatch>();

  const addPatch = (path: string | undefined, action: FilePatch["action"], content?: string) => {
    if (!path?.trim() || content === undefined) return;
    const resolvedContent = overrideMap.get(path) ?? content;
    patches.set(path, { path, action, content: resolvedContent });
  };

  for (const file of buildPreview.files ?? []) {
    if (file.action === "delete") {
      patches.set(file.path, { path: file.path, action: "delete" });
      continue;
    }
    addPatch(file.path, file.action, file.content);
  }

  addPatch(buildPreview.componentPath, "update", buildPreview.componentContent);
  addPatch(buildPreview.storyPath, "update", buildPreview.storyContent);

  for (const [path, content] of overrideMap) {
    if (!patches.has(path)) {
      patches.set(path, { path, action: "update", content });
    }
  }

  return [...patches.values()].filter(
    (patch) => patch.action === "delete" || Boolean(patch.content?.trim()),
  );
}

export function resolvePullRequestPatches(
  buildPreview: JobBuildPreview,
  options: {
    patches?: FilePatch[];
    previewFileOverrides?: Array<{ path: string; content: string }>;
  },
): FilePatch[] {
  const clientPatches = (options.patches ?? []).filter(
    (patch) => patch?.path?.trim() && (patch.action === "delete" || patch.content?.trim()),
  );
  if (clientPatches.length > 0) {
    return clientPatches;
  }

  return buildPatchesFromJobPreview(
    buildPreview,
    options.previewFileOverrides?.map((file) => ({ path: file.path, content: file.content })),
  );
}

export function buildPullRequestBody(stored: StoredJob): string {
  const lines = [
    "## Fig2Code",
    "",
    `Component: **${stored.componentName ?? stored.request.prunedSpec.name}**`,
    `Intent: \`${stored.intent}\``,
    `Job: \`${stored.id}\``,
  ];

  if (stored.codegenSummary) {
    lines.push("", "### Summary", "", stored.codegenSummary);
  }

  if (stored.changeSummary?.changes?.length) {
    lines.push("", "### Changes", "");
    for (const change of stored.changeSummary.changes) {
      lines.push(`- ${change.text}`);
    }
  }

  lines.push("", "---", "Generated by Fig2Code.");
  return lines.join("\n");
}

export function buildManualPullRequestBody(componentName: string): string {
  return [
    "## Fig2Code",
    "",
    `Component: **${componentName}**`,
    "",
    "Manual edits from the Fig2Code preview.",
    "",
    "---",
    "Generated by Fig2Code.",
  ].join("\n");
}

export interface OpenPullRequestFromPatchesInput {
  vcs: StoredJob["request"]["vcs"];
  auth: { token: string; atlassianEmail?: string };
  componentName: string;
  targetBranch: string;
  patches: FilePatch[];
  branchSuffix: string;
  body?: string;
}

export async function openPullRequestFromPatches(
  input: OpenPullRequestFromPatchesInput,
): Promise<OpenJobPullRequestResult> {
  const { vcs, auth, componentName, targetBranch, patches, branchSuffix, body } = input;

  if (patches.length === 0) {
    throw new Error("No file changes to include in the pull request");
  }

  const headBranch = `fig2code/${slugify(componentName)}-${branchSuffix.slice(0, 8)}`;
  const git = createGitHostProvider(vcs.provider);

  await git.writeFiles(vcs, auth, {
    headBranch,
    baseBranch: targetBranch,
    message: `Fig2Code: ${componentName}`,
    patches,
  });

  const pr = await git.openPullRequest({
    vcs,
    token: auth.token,
    atlassianEmail: auth.atlassianEmail,
    headBranch,
    baseBranch: targetBranch,
    title: `Fig2Code: ${componentName}`,
    body: body ?? buildManualPullRequestBody(componentName),
  });

  return {
    prUrl: pr.url,
    prNumber: pr.number,
    headBranch,
  };
}

export async function openJobPullRequest(
  input: OpenJobPullRequestInput,
): Promise<OpenJobPullRequestResult> {
  const { stored, targetBranch, previewFileOverrides } = input;
  const buildPreview = stored.buildPreview;

  if (!buildPreview) {
    throw new Error("Job has no build preview — validate codegen before opening a PR");
  }

  const patches = resolvePullRequestPatches(buildPreview, {
    patches: input.patches,
    previewFileOverrides,
  });

  if (patches.length === 0) {
    throw new Error("No file changes to include in the pull request");
  }

  const componentName = stored.componentName ?? stored.request.prunedSpec.name;
  return openPullRequestFromPatches({
    vcs: stored.request.vcs,
    auth: {
      token: stored.secrets.gitToken,
      atlassianEmail: stored.secrets.atlassianEmail,
    },
    componentName,
    targetBranch,
    patches,
    branchSuffix: stored.id,
    body: buildPullRequestBody(stored),
  });
}
